---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: shared
spec:
  encryptedData:
    password: AgAjWQEr+NdvPDF/SOwZwzZwsn5PXpFl1k8i/ylouOlMmX2FSdQO5ZR54JDpkiIhSvhlUI5uYTd3bUoARErs6tqBpES6WFqYhdq4RANTrLynkJsZJ0zvze8oX7p7m25uRAWwgsHICIShOi/9cRRIg4LuCS8sH9QKTCYC7SxfM6FA+MA3w0C0FeOYKTGsVoAvd97RVOWSSTvLox82PLuxC69R01o5HRGD9TOWchIkY1k6trErkEC6V38NNVL4kk+Vm+fWnm9Wqju7hQDSXb3lRwOGQ0PHX4cId4nEm9u+Bxnre57vwx8l0aV/kl2IoV9Pdg+0BAxmnOQ4D6FoZVsHNmq+YAkhh0/pg5YINbMCRvACub1tv+/1sc6o2NF0EGhlk0jOiAL9bvQqYmDpXJgl7f0478aXDeXgi0i4Pjfl9mwkZD24RJsPgsv8T1/VcGp58mF/LsXea6pBWO8tSuaA1cnPIt5og90q4OA8BF6YRdlCe2Bw1svrFrOIlcNSGjyQyde0BPPgmicp6W4KtwPpa6JdKisAtSVf4zn05WrJhJQavfDagV6A9occXNLs69hE1BdyzouJm65atH02t64dGDS4t+q//7bkmKVBg/A6rV0oWxlAKiaLtu/ZmklbZGDc4CxwNX9aGukiBjuEAmKhRIG8HpkWudeYjOpSFy/2TzlBgW53yA6HlAs+hVRpm6lAok6zL1qzYlKEqA==
  template:
    metadata:
      name: postgres-secret
      namespace: shared
