---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    password: AgBCiMPZvIXx8TYNJ3gWk6d4IwlJ5zE+qaznMvMqvno3AWKUkXO/n9eX5+90OE4MyiKjnsP7PzfXHSkND6BXxTF1F16MeU4mD96UR66QZCPEvJ3QVgo6Kj9fcnL+G5Q0uzCTZVf/v+fW8gm1khN6erdrLvr7MTV1KD0D1u3JPo0Pr2UkCLZjfCU7L/nTJR27oeahJE8vAxVzWWaJB/ywAuKzzYbG4YQjdz8DT88LbgoGHNWpB1VfoUl8eOB1nYrkYi89lyx4U4cAas96jfSsSU7XspXM/1r3ldspPZqmRA/yaMxAogHnSPBFqO2ScFGRmgrta+79lSHegbj8nhvMtfR5Z8IESuINF4bKAKKIF/G+KvoXxuXgP4vkFUVCZhX88E4e5OgfkfLBbGplx8r1Tup+AerkMUeJYRpad44hlTmrnJn0r1zXRz6FZaRNTQ/Y7esDtgkg0bcTw0/B1IvTWJkrdq0LDW1hnFcVVt16pAY9+fw32oAIR2eh1nuBc1Y4iPy9b1cXAJtlrfrsiR1F8yx5vUAH6ODyr+lmzAjd2qMwD77uMo0UOGVd6aLuTTrPfn2t9ykr1LaMXfxVTx1Ugr/aPd/UggDJHXuPs5YYMamwi+gmHiVv1tUislkdgsqKOGF8TPdgCCBfw6pQwz+IEU3h2+gQUVL0370Z+s8UCwREa58RBoRa+rvUYc49vS47Ex/IuI0r473kiA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
    type: Opaque
